# Generated by Django 2.2.1 on 2019-05-12 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Event', max_length=50)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Kids', 'Kids'), ('Concerts', 'Concerts'), ('Education', 'Education')], max_length=15)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('city', models.CharField(choices=[('Lviv', 'Lviv'), ('Kyiv', 'Kyiv'), ('Kharkiv', 'Kharkiv'), ('Dnipro', 'Dnipro'), ('Lugansk', 'Lugansk')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
